
GET http://localhost:5050/property/getAll

##########

GET http://localhost:5050/property/find/latest

##########

GET http://localhost:5050/property/find/byquery?priceRange=100000-200000&type=single home&location=Milano

##########


GET http://localhost:5050/property/find/648c80ffd500a2a47fadd858

##########

POST http://localhost:5050/property HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGM4MGZmZDUwMGEyYTQ3ZmFkZDg1OCIsImlhdCI6MTY4NzU0MDQ0OCwiZXhwIjoxNjg3NTU4NDQ4fQ.Gynv2rHXbLzF6agmlyM9jRTorpjyPaTioNS1WUOMx3g

{     
      "seller": "648c80ffd500a2a47fadd858",
      "title": "property5",
      "description": "property5description",
      "type": "single home",
      "img": "https://www.casetraprivati.it/immobile/44046/cover?fmt=tmb",
      "price": 250000,
      "squaremeters": 150,
      "location": "Capannori",
      "bedrooms": 8,
      "latest": true
}

##########

PATCH http://localhost:5050/property/648c80ffd500a2a47fadd858 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGM4MGZmZDUwMGEyYTQ3ZmFkZDg1OCIsImlhdCI6MTY4NzE3Mzg3MCwiZXhwIjoxNjg3MTkxODcwfQ.iEBs_xnD54-Zun4ixyEJhvNMnP6aGae4HKi-5hUFYlY

{     
      "seller": "648c80ffd500a2a47fadd858",
      "title": "property5",
      "description": "property5description",
      "type": "single home",
      "img": "https://www.casetraprivati.it/immobile/44046/cover?fmt=tmb",
      "price": 150000,
      "squaremeters": 200,
      "location": "Capannori",
      "bedrooms": 8,
      "latest": true
}

##########

DELETE http://localhost:5050/property/64903a006dc44aed9190ef34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OGM4MGZmZDUwMGEyYTQ3ZmFkZDg1OCIsImlhdCI6MTY4NzE3Mzg3MCwiZXhwIjoxNjg3MTkxODcwfQ.iEBs_xnD54-Zun4ixyEJhvNMnP6aGae4HKi-5hUFYlY